### PR TITLE
Fixed DocumentSelection#_fixGraveyardSelection

### LINKED ISSUE #1046: DocumentSelection: fixed range ends up in incorrect place
Whenever a range from `DocumentSelection` becomes moved to graveyard due to removing nodes around it, `DocumentSelection#_fixGraveyardSelection` is fired and the situation is fixed.

The algorithm works incorrectly when the whole content is removed though. If that happens, `root [ 0 ] - [ 0 ]` range is added to the selection. This wasn't well thought. Such range is probably incorrect. It may have even more consequences, like adding `inlineFiller` in wrong place, etc.

Instead of adding incorrect range, no range should be added. This would mean that if no other range was in the selection (which is true if all contents were removed), the "default range" would be returned.

The default range is better than `root [ 0 ] - [ 0 ]` `LiveRange` because it will become correct as soon as any content is added to the document.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fixed: `DocumentSelection#_fixGraveyardSelection` now does not add incorrect range when all content is removed from document, instead it is empty. Closes #1046.

### CODE REVIEW

**Comment by Reinmar** [comment]
Did you check all tests?

**Comment by scofalik** [comment]
I've run `npm t`, though I might have out-dated other repos. Is something wrong? It looks like the build that failed had passed all the tests.

**Comment by Reinmar** [comment]
> Is something wrong?

IDK, I just asked because this is the kind of change which might've broken something.

**Comment by scofalik** [comment]
I've run `npm t` and clicked a bit (but not much) in manual test.

**Pull request merged**
