### PR TITLE
Improved efficiency of Differ.

### PR DESCRIPTION
**Pull request by oskarwrobel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Fixed problem with handling very large text nodes. Part of https://github.com/ckeditor/ckeditor5/issues/1875.

---

### Additional information

*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*

### CODE REVIEW

**Comment by pjasiun** [comment]
Thanks to this fix there is no error but the editor still works super slow with the content provided in the ticket. However, it is not a scope of this PR.

**Comment by oskarwrobel** [comment]
Unfortunately, the test takes too long for CI and it leads to a timeout. I need to remove unit tests for this change.

**Comment by Reinmar** [comment]
Did you try to use `concat()` too? Did you measure the performance of this solution?

**Comment by oskarwrobel** [comment]
Nope, I focused on making the editor not crash. The issue is still open for performance improvements.

**Comment by oskarwrobel** [comment]
Looks like concat may be faster:

image

**Pull request merged**
