### PR TITLE
T/1053 Incorrectly set context.forceWeakRemove for MergeDelta during OT

### LINKED ISSUE #1053: OT: incorrectly set context.forceWeakRemove for MergeDelta
This is how `context.forceWeakRemove` is set now:

```javascript
context.forceWeakRemove = !( originalB instanceof RemoveDelta && !history.isUndoneDelta( originalB ) );
```

This means that it is `true` whenever `originalB` is not `RemoveDelta`. This is wrong. Not only `RemoveDelta` has `RemoveOperation`. This causes a bug when transforming `MergeDelta`, described here: https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313444977

Actually, since `context.forceWeakRemove` is used only for `RemoveOperation` x `MoveOperation` transformation, we can safely get rid of first part of this condition: `originalB instanceof RemoveDelta`. The flag doesn't have to have meaningful value if given delta has no `RemoveOperation`s.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fixed: Fixed bug when additional list item has been created when undoing setting block quote on list followed by splitting list item in that list. Closes #1053.

---

### Additional information

1. When working on this issue I discovered another one. `RemoveOperation` x `MoveOperation` was changing `context.isStrong` value directly, which affected further transformations. Now `context.isStrong` is assigned to a different variable and that variable is changed if needed.

2. Tests for this issue will be written in `ckeditor5-undo`.

### CODE REVIEW

**Comment by scofalik** [comment]
Tests: https://github.com/ckeditor/ckeditor5-undo/pull/69

**Comment by Reinmar** [comment]
Tests for this change need to also be in this package. There can be additional integration tests in ckeditor5-undo but we need some basic verification here. Otherwise, someone (most likely you) will complain that he changed something in ckeditor5-engine, tests passed, but they failed in ckeditor5-undo ;).

**Comment by scofalik** [comment]
I will write the test but you have to be aware that these kinds of tests are difficult to write in "non-integrational" way.

**Comment by Reinmar** [comment]
But I didn't say that the test must be non-integrational. I just want it to be here. And there's a whole range of approaches and API levels between tests in the undo package and unit tests (which we don't want). In other words – I'd like to see as high-level test as you could implement in here.

**Comment by scofalik** [comment]
I know I know :). I just wanted to explain why I haven't written any test in the first place.

**Comment by scofalik** [comment]
I've added additional test (and also find another conceptual problem and fixed it).

**Pull request merged**
