### PR TITLE
T/889 Fixing tests in SelectionObserver

### LINKED ISSUE #889: SelectionObserver test is unstable
https://travis-ci.org/ckeditor/ckeditor5/builds/214216219#L1295

"SelectionObserver should warn and not enter infinite loop" started failing recently.

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Improved tests stability by changing how infinite loop detection works in SelectionObserver. Closes #889.

---

### Additional information

We decided to totally remove checking if selection is same as previous. Only counter is used now and I've manually tested its settings. I've decided that it will be cleared each second and warning will be showed if counter is greater than `200` before that time. I've managed to get the counter to `~150` by dragging selection around inline elements.

### CODE REVIEW

**Comment by Reinmar** [comment]
Hm... I'm afraid that this check stops making any sense when it has to hit 200 in 1s. Even if we'll have a real inf loop it may happen that it simply won't exceed this number.

Actually, this is exactly what happens now. The issue we have with `selectionChange` being fired up to 100 times per second when you drag the mouse is exactly an infinite loop (see #887). So, instead of avoiding catching it we should exactly catch those moments. I feel (after doing a very quick check ;)) that the right number is something around 50 events per second. I was able to trigger around ~30 normal selection change events by dragging (up to ~50 when I moved my mouse super quick) and the results were very similar on FF and Chrome. Any number higher than that has a high probability of being an inf loop. And it's better to log a warning and cancel `selectionChange` event (which has nearly invisible repercussions in such a case) than let the browser fall into inf loop.

Therefore, let's go lower with the number and see how often we'll get the warning. This will be a good way of checking how we do with #887. (cc @f1ames)

I'd propose 60 events per sec. This is around the frame rate at which I'd suppose the browser may be interested in checking the mouse position.

**Comment by pjasiun** [comment]
Note that this check is not any real solution. It's here only to prevent browser freezing in case of the infinite loop. We should not use it to prevent or hide any real bug, only change freeze into console message.

Despite that we should not show a warning in cases we accept as normal behavior, I agree with @Reinmar that we could use this mechanism also to find buggy behavior, so it makes sense to set this limit low.

**Comment by Reinmar** [comment]
> We should not use it to prevent or hide any real bug, only change freeze into console message.

Exactly. That's why we're working on #887. But exactly that bug should be caught by this check.

**Comment by Reinmar** [comment]
There's one thing which worries me:
mar-28-2017 16-58-49

This happens on master and on this branch. We should get just one warning, not 60. I somehow understand why is this happening, but I have a feeling it's not good.

**Comment by Reinmar** [comment]
BTW, it always happens exactly 63 times :D.

**Comment by Reinmar** [comment]
I made such a change to catch any `render()` calls after the inf loop was caught:

image

Turns out that `render()` is never called after that. Which means that those native `selectionChange` events which we're handling are not triggered by us. Which means that with a high certainty they are triggered before we stop rendering and are in some kind of a buffer waiting to trigger our listener. And it even makes quite a lot of sense.

**Comment by Reinmar** [comment]
I wanted to say – let's reset the counter after logging the warning... but nope – this is a very wrong idea. The stacked events will cause rendering on and on.

**Comment by Reinmar** [comment]
This does the trick:

```js
this.stopListening( domDocument, 'selectionchange', this._callback );
setTimeout( () => {
	this.listenTo( domDocument, 'selectionchange', this._callback );
} );
```

But I guess it's unnecessary. Since render() isn't called after we kill the loop we're pretty safe. Only the warning gets duplicated.

**Pull request merged**
