### PR TITLE
[WIP] Focus the new editing host to workaround FF's errors

### PR DESCRIPTION
**Pull request by Reinmar**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Fixed a bug where Firefox would throw an `NS_ERROR_FAILURE` error when moving selection from a nested editable to the root editable. Closes ckeditor/ckeditor5#721.

---

### Additional information

This is WIP. @Mgsy could you check whether this PR doesn't cause some regressions? Unfortunately, you'd need to check all browsers and various scenarios because such a change has a huge spectrum of potential regressions.

### CODE REVIEW

**Comment by Mgsy** [comment]
I've checked your fix and it works fine. I haven't noticed any regression.

**Comment by Reinmar** [comment]
OK, then let's add a manual test and automated test (if possible). I leave that to you, @ma2ciek

**Comment by ma2ciek** [comment]
Should I add the manual test to the engine or to the image package?

**Comment by Reinmar** [comment]
Here, in the engine.

**Comment by Reinmar** [comment]
If it was a normal manual ticket test putting it into the image might make more sense. But in this case, when this is engine's feature (nested editables), let's have it here.

**Comment by ma2ciek** [comment]
Ok, so I'll also add `ckeditor5-image` to `ckeditor5-engine`'s `devDeps`.

**Comment by Reinmar** [comment]
That can be a strictly engine's test. With a pseudo widget.

**Comment by ma2ciek** [comment]
I've added a manual test to that bugfix.

**Pull request merged**
