### PR TITLE
T/179 Converters API

### LINKED ISSUE #179: TreeModel to TreeView conversion controller
- Converter will listen on the change event on the Tree Model and modify Tree View using Writer class (https://github.com/ckeditor/ckeditor5-core/issues/164).

- It will be configurable, by callbacks fired for every converted item (element, text, attribute).

- Whole text with the same attribute will be a single converted item ("f" ( bold ), "o" ( bold ), "o" ( bold ), "b", "a", "r" will fire two text conversion events: one for "foo" and one for "bar").

- Callbacks can be assigned to the specific item types, because of the performance.

- It will be possible to register generic callback, called every time.

- Callbacks will have priorities.

- User will be able to set the position for the next converter callback (mess the document, and said where the conversion cursor should be put), by default the cursor will be moved to the next position.

- Each step will have a list of items to consume (text, element, attributes), and methods:
   - `consume` - will remove item from that list,
   - `isConsumed` - check if the item has been consumed.

- The list of items to consume will shrink, not grow, because we would end up with the whole list next to each item at the end of the conversion. We could initialise the list when it is used for the first time on each item.

- Generic attribute may be consumed by the specific converter, for example image converter may consume bold attribute on the image, so we will have `` instead of `<b></b>`

- There will be tool to create basic converter (e.g. attribute converter).

### PR DESCRIPTION
**Pull request by scofalik**
This PR brings Converters API in `treeController` namespace. Fixes #179 #180 . There will be a number of follow-up issues but the core for converters is already ready to be used.

Follow-ups:
#296 (This is the main follow-up, this issue should be the next step of taking care of converters.)
#266 (It appeared that it is important to have this feature. We can try to workaround it but it makes some converters complicated and some maybe even impossible.)
#267 (As above.)

(Refactor stuff. We sooner we will do it, the less we will have to re-write):
#348
#349
#350
#351
#353
#355
#356

### CODE REVIEW

**Comment by pjasiun** [comment]
You should not change `DataController` and `EditingController` there is a separate ticket for it.

**Comment by pjasiun** [comment]
We should ensure that View to Model converters flattens structure. I mean that if only text is supported then `<b>foo<i>bar<u>bom</u></i></b>` will return [ 'foo', 'bar', 'bom' ], not [ 'foo', [ 'bar', [ 'bom' ] ] ].

**Comment by scofalik** [comment]
I've added a list of follow-ups to the first post.

**Comment by scofalik** [comment]
I've added a test you requested and tried to clean up mess with editing/data controllers.

**Comment by pjasiun** [comment]
I like the code, docs, tests and examples. We could now discuss docs, for instance if the `ModelConsumable` should have an example of a `modelConversionDispatcher` listener. But I think that part of this documentation need to be moved to the architecture docs anyway and we will be able to make docs better when we will have architecture docs. We could also spend some time improving advance tests, but their purpose was to prove it is possible what they did.

I think it is time to close it. Good job!

**Pull request merged**
