### PR TITLE
Range#_getTransformedBySplitOperation will expand the range if insertionPosition is equal to the range end

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: `Range#_getTransformedBySplitOperation` will expand the range if `insertionPosition` is equal to the range end. Modified transformations to align with that change. Closes https://github.com/ckeditor/ckeditor5/issues/1278.

### CODE REVIEW

**Comment by scofalik** [comment]
Updated, sorry.

**Comment by Reinmar** [comment]
image

The same scenario, but undo, redo:

oct-05-2018 11-00-06

**Comment by scofalik** [comment]
Actually, this is a little different scenario. In the original one selection was collapsed. Please move it to a separate ticket, thanks.

**Comment by Reinmar** [comment]
You're right, I'm reporting it to a separate ticket.

**Comment by Reinmar** [comment]
Here it is: https://github.com/ckeditor/ckeditor5/issues/1287.

**Pull request merged**
