### PR TITLE
T/2016: Introduced support for "keyup" event.

### LINKED ISSUE #1026: Support for `keyup` event on document
In order to detect whether the user keeps the <kbd>Backspace</kbd> key, we need to add support for the `keyup` event called on `Document`.

It's required in order to implement a test case **II** from here – https://github.com/ckeditor/ckeditor5-typing/issues/61#issuecomment-314705304.

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: `KeyObserver` will handle the `keyup` event. Message. Closes #1026.

### CODE REVIEW

**Comment by Reinmar** [comment]
Misses `keyup` event API docs.

**Comment by Reinmar** [comment]
Did you check that it works and we have two events (keydown and keyup) with proper attributes?

**Comment by pomek** [comment]
image

IMO works as it should.

**Comment by Reinmar** [comment]
I meant documentation.

**Comment by pomek** [comment]
After a fix added in bccf3f4 it works well:

image

**Pull request merged**
