### PR TITLE
Added Schema#limits and integrated it with data controller's modifySelection

### LINKED ISSUE #818: Integrate various algorithms with schema#limits
We need to add `Shema#limits` https://github.com/ckeditor/ckeditor5-engine/issues/532#issuecomment-278900072 to improve compatibility of our algorithms with nested editables like `ImageCaption`.
I will create separate issues in features that needs this improvement, I want to gather here a list of places where change will be needed:

- enter should not break `limit` elements: https://github.com/ckeditor/ckeditor5-enter/issues/38,
- backspace should not move selection outside empty `limit` elements
output

Any other ideas?

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Added `Schema#limits` and integrated it with data controller's modifySelection. Closes #818.

### CODE REVIEW

**Comment by szymonkups** [comment]
Please close together with https://github.com/ckeditor/ckeditor5-enter/pull/39.

**Comment by Reinmar** [comment]
I fixed the failing tests, but there are missing tests for `modifySelection()`:

image

**Comment by Reinmar** [comment]
Also, one important thing to notice is that you check only the immediate parent of the selection (whether it's a block or not). We don't have yet a case for that but you may have:

```html
<caption><paragraph>^</paragraph></caption>
```

And the selection must not be extended to the left in this case.

**Comment by Reinmar** [comment]
More things:

* This PR desc is wrong – the limits are integrated with all the DC's methods, not just `modifySelection()`.
* I'm able to paste a block content into an image caption if I paste at the end of it. If I paste in the middle the https://github.com/ckeditor/ckeditor5/issues/404 occurs. The first must be blocked – the insertion should not leave the limit element. The latter may be a bug in `insertContent()` too so you can give it a try fixing it.

**Comment by Reinmar** [comment]
I'm going to take over the PR from here, @szymonkups.

**Comment by Reinmar** [comment]
Warning for the future (and fun fact too :P). The added `modifySelection()` test looked like this:

```js
test(
	'should not extend to outside of inline limit element',
	'<inlineLimit>foo[]</inlineLimit>',
	'<inlineLimit>foo[]</inlineLimit>'
);
```

(it was meant to test that the selection won't leave a "limit" element)

It passed. At the same time, the CC dropped below 100%. So what's wrong here?

Two things actually.

First – if the test was written before the code was modified (TDD!) you'd know that it passes without any changes in the code.

Why? Because the test is too limited. It tests the behaviour in too narrow context. Namely – the selection has no place to go wrong – there's no text outside the `<inlineElement>` :D.

When writing such tests I'm very often adding some additional elements or text nodes at the both ends of the content. I also try many variations and one or two more complicated scenarios where more things could go wrong. This, even though might be a bit exaggerated at the beginning (because you can have 100% CC a lot earlier), makes sure the algorithm stays stable in the future, when some inevitable refactoring touches it.

**Comment by Reinmar** [comment]
Okey dokey, I added a lot of tests for all 3 functions – `modifySelection()`, `insertContent()` and `deleteContent()`. I had to reimplement `modifySelection()` and I took this opportunity to change the semantics a bit. Now, the focus will be placed in the first position where text is allowed. This simplified the implementation a lot and handled a lot of cases, including some from #710. In case of other functions, I made sure that limit elements are never left or changed (e.g. merged with other elements in case of `deleteContent()`).

Based on my manual tests, all works fine now :).

**Pull request merged**
