### PR TITLE
T/165 engine.view API unified with model

### LINKED ISSUE #165: Tree view and tree model APIs should be simmilar
Both data structures use the thee structures which allows attributes and child nodes manipulating. We should ensure that if both have `insertChildren` method, then both of these methods have the same order of parameters.

AFAIR, beside https://github.com/ckeditor/ckeditor5-core/issues/76, we need to introduced `element.appendChildren` to the tree model element.

### PR DESCRIPTION
**Pull request by scofalik**
Fixes #165.

This PR bases on #480, PR #537 -- it includes that PR. Please review it only after #537 is merged.

### CODE REVIEW

**Comment by scofalik** [comment]
For now I decided to skip getters/setters unification across model and view. It can be done in #518. I only brought missing API parts but some of them are getters in model and methods in view and vice versa.

I also wasn't really sure what to do about `Node#getPath()` in model vs `Node#getAncestors()` in view. I ended up not adding `getAncestors` to model and `getPath` to view. I assumed they do similar thing, and since model positions bases on paths while view positions bases on element+offset it makes sense.

**Comment by scofalik** [comment]
Since `t/480` got merged into `master`, I rebased this branch with `master` too. Now it's just one commit.

**Comment by pjasiun** [comment]
We do not need `Node#getPath()` in the view, there is nothing like path used in model position. But we may need `Node#getAncestors()` in the model.

**Comment by scofalik** [comment]
I've added `engine.model.Node#getAncestors`.

**Pull request merged**
