### PR TITLE
Added model.DocumentSelection#hasOwnRange.

### LINKED ISSUE #1137: Introduce a way to check if DocumentSelection has only a default range
I propose introducing `DocumentSelection#hasOwnRange` as a way to check whether ranges set in selection are set directly (for example via `.addRange()` or `.setRanges()`) or is it just the default range.

This is needed to fix a bug in undo selection restoring.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Introduced `model.DocumentSelection#hasOwnRange`. Closes #1137.

### CODE REVIEW

**Comment by Reinmar** [comment]
OMG, like `hasOwnProperty()` :D. Do we have to use it in all for-of loops now? :trollface:

**Comment by Reinmar** [comment]
OK, by my above comment you can clearly see that I did not understand what this property is all about. Which means that it might be worth rethinking its name.

**Comment by Reinmar** [comment]
Nothing better came to my mind so let it be `hasOwnRanges`.

**Comment by scofalik** [comment]
My other ideas were `isSet` or `isDefault`.

**Pull request merged**
