### PR TITLE
Fixed: `view.Renderer#render` will now always create inline filler at expected position.

### LINKED ISSUE #1014: view.Renderer does not create inline filler in newly created DOM elements
As the title says.

At the moment, inline filler is handled by `view.Renderer#_updateChildren`, but only if the filler is directly in the updated children. Howeer, newly created items are not processed directly by `_updateChildren` and do not receive inline filler.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fixed: Fixed a bug where inline filler was not always created after rendering or selection change. Closes #1014.

### CODE REVIEW

**Comment by pjasiun** [comment]
The change is fine for me but because it is 6:15 PM I prefer to wait with merging till tomorrow.

**Comment by pjasiun** [comment]
Or, nevermind. Works great :)

**Comment by scofalik** [comment]
> The change is fine for me but because it is 6:15 PM I prefer to wait with merging till tomorrow.

> Or, nevermind. Works great :)

You are a brave man, PJ, and today's world needs brave men like you.

**Comment by Reinmar** [comment]
LGTM, except "DOM" => "the DOM" in all occurrences ;)
I'll fix the comments and docs.

**Pull request merged**
