### PR TITLE
Changed pattern to collect all characters

### PR DESCRIPTION
**Pull request by pomek**
Fixes: #436

Unfortunately, the tests are missing because I don't have enough knowledge how it should look. 

OTOH, I talked F2F @pjasiun and we decided - if creating tests will be problematic, we can skip it.

### CODE REVIEW

**Comment by Reinmar** [comment]
We shouldn't skip writing any tests. I don't think that this isn't testable at all – perhaps it requires some knowledge. So I'd recommend passing this issue to someone else.

**Comment by pjasiun** [comment]
> OTOH, I talked F2F @pjasiun and we decided - if creating tests will be problematic, we can skip it.

But then we realised that this parameter is not checked at all, so it is a bigger bug, isn't it? If so, changing the value does not fix anything.

**Comment by pomek** [comment]
I had a test like this:

```js
// add attribute 'data-attr' to textAttributes array
// allow to have attribue 'data-attr' for span element (in schema)

it( 'should convert from view attribute to model attribute (2)', () => {
	const dataAttrValue = `Lorem\n\tipsum\tdolor\t\tsit\n\namet.\t.\n\t.`;

	buildViewConverter().for( dispatcher ).fromElement( 'span' ).toElement( 'span' );

	buildViewConverter().for( dispatcher )
		.fromAttribute( 'data-attr' /*, /[0-9]+/*/ )
		.toAttribute( ( viewElement ) => ( {
			key: 'data-attr',
			value: viewElement.getAttribute( 'data-attr' )
		} ) );

	const result = dispatcher.convert( new ViewContainerElement( 'span', { 'data-attr': dataAttrValue }, new ViewText( 'foo' ) ), objWithContext );
	modelRoot.appendChildren( result );

	expect( modelToString( result ) ).to.equal( `<span data-attr="${ dataAttrValue }">foo</span>` );
} );
```

I tried to modify the second parameter for `buildViewConverter.fromAttribute()` and nothing happens. Above tests always passed.

**Comment by pjasiun** [comment]
The test looks fine. It means that this parameter is, most probably not checked at all. And most probably it is not passed to the `Matcher` correctly. 

It needs to be debugged. You can report a separate issue or add a comment to this one and expand the scope of it (and rename it). Anyway, changing the default value of the parameter which is not checked in the first place is pointless.

**Comment by pomek** [comment]
I've created a new one ticket for it - https://github.com/ckeditor/ckeditor5-engine/issues/588

**Comment by pjasiun** [comment]
I'm closing this PR for now, since we need to fix a different bug which we are not planning to work on right now.

**Pull request closed without merging**
