### PR TITLE
Removed the "model.Writer#setTextData()" method

### LINKED ISSUE #1363: Should model.Writer#setTextData() be removed?
I can't see it used... and it shouldn't be used at all because it changes the text node's data directly:

```js
	/**
	 * Sets the text content for the specified `textNode`.
	 *
	 * @param {String} value New value.
	 * @param {module:engine/model/text~Text} textNode Text node that will be updated.
	 */
	setTextData( value, textNode ) {
		textNode._data = value;
	}
```

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Removed the unnecesary  `model.Writer#setTextData()` and `view.Writer#setTextData()` methods. Closes #1363.

Should be merged with https://github.com/ckeditor/ckeditor5-list/pull/102.

### CODE REVIEW

**Comment by Reinmar** [comment]
You didn't check whether this method is used somewhere... and it is.

@scofalik, I checked that we can't simply remove this bit: https://github.com/ckeditor/ckeditor5-list/blob/d2023267caa88eb383b1fab773e137c233cf5b8d/src/converters.js#L455-L462

Do you think that we could use `writer.remove()` there to remove these trailing spaces?

**Comment by Reinmar** [comment]
BTW, it seems that we can also fix https://github.com/ckeditor/ckeditor5-list/issues/101 easily because it should also have access to the writer.

**Comment by pomek** [comment]
> You didn't check whether this method is used somewhere... and it is.

So the `view.Writer#setTextData()` isn't used anywhere.

**Comment by Reinmar** [comment]
> So the view.Writer#setTextData() isn't used anywhere.

May be true. We both got a bit confused when discussing this in #1363 with @pjasiun.

Anyway, the `model.Writer#setTextData()` should be removed not because it's barely used, but because it's dangerous. You cannot change the text like this in the model.

**Comment by Reinmar** [comment]
Model writer offers a simple `writer.remove()` method which accepts a range. Based on this you can remove a piece of text. I think that it will be the most optimal solution.

A simpler solution would indeed be replacing an entire text node, but then we need to take care of its attributes. That's a bit worse to me.

**Comment by pomek** [comment]
Everything sounds good but the write instance is the instance of the model but the `child` is an instance of the view. So at this moment, `model.setTextData()` changes value of the view.

**Comment by scofalik** [comment]
I am for `view.Writer#remove` if it wasn't resolved yet.

**Comment by Reinmar** [comment]
OK, this is a deeper problem. And it's the same problem as in https://github.com/ckeditor/ckeditor5-list/issues/101 – we need a view writer somewhere. And we need a place to clean up the view being converted.

For now, let's use protected methods of view text nodes to change their data. This will be in line with what we have reported in https://github.com/ckeditor/ckeditor5-list/issues/101.

**Comment by pomek** [comment]
https://github.com/ckeditor/ckeditor5-list/pull/102

This PR is ready to review once again.

PS: I fixed failed, not related to my changes test.

**Pull request merged**
