### PR TITLE
Fix docs and provide missing tests for the `DataController#insertContent`

### LINKED ISSUE #895: DataController.insertContent() and insertContent event have incorrect docs
We allowed passing an element to `insertContent()` function, but the docs of the method and event weren't updated and the change weren't tested on `DataController.insertContent()`.

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Added missing test and updated docs in the `DataController#insertContent`. Closes #895.

### CODE REVIEW

**Comment by Reinmar** [comment]
What about tests?

**Comment by ma2ciek** [comment]
I talked about the tests on the issue page (#895)

**Comment by ma2ciek** [comment]
I added a test for this change.

**Comment by Reinmar** [comment]
The `DataController.insertContent()` still doesn't have a test how it works with an item, but we can live with that. However, if you changed docs of two things (event and method) the same should ideally be reflected by the tests.

**Comment by ma2ciek** [comment]
But the method `DataController.insertContent()` fires only an event (https://github.com/ckeditor/ckeditor5-engine/blob/3da3d625fc33a669c34c9f3ac857c2f90caa57de/src/controller/datacontroller.js#L259), so is this check necessary as we can pass everything to this method and the test will pass? (maybe I'm wrong, but for me one test is good enough).

**Pull request merged**
