### PR TITLE
Undo and redo no longer crashes in scenarios featuring pasting content into earlier pasted content

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Undo and redo no longer crashes in scenarios featuring pasting content into earlier pasted content. Closes https://github.com/ckeditor/ckeditor5/issues/1385.

---

### Additional information

Requires https://github.com/ckeditor/ckeditor5-undo/pull/96/files

I had to re-introduce `forceWeakRemove` flag. This mechanism/flag was used before when we had deltas. I figured it was no longer needed after the refactorings we had. It wasn't needed for long, however, unfortunately, those cases need it. They can't be solved in a way other than explicitly saying: "this is undo, do (not) do this or that".

@Mgsy please test *extensively* undo after this PR as it touches multiple scenarios. Please test scenarios with merges, splits and removes. All unit tests were fine, though.

### CODE REVIEW

**Comment by Reinmar** [comment]
I pasted the same content twice and undid that twice and additional list item was left:

feb-18-2019 09-59-41

**Comment by Reinmar** [comment]
ok, I can see that this is an unrelated issue. I'll extract it to a separate ticket. @Mgsy, unless you know about similar ticket already?

**Comment by Mgsy** [comment]
>@Mgsy, unless you know about similar ticket already?

AFAIR, we don't have it reported.

**Comment by Reinmar** [comment]
Reported: https://github.com/ckeditor/ckeditor5/issues/1540

**Pull request merged**
