### PR TITLE
Make setting "undo mode" in transformation more explicit

### LINKED ISSUE #1146: Undo mode is not recognized properly during deltas transformations
We have `context.aWasUndone` and `context.bWasUndone` and they were used to check whether transformation is in "undo mode" and if special cases should be applied. However this is wrong in some situations (during selective undo). Transformation algorithms should recognize that they are in undo mode straight away and always when we are transforming for undo. This should not been based on history and whether some delta was undone or not.

### PR DESCRIPTION
**Pull request by scofalik**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Internal: Make setting "undo mode" in transformation more explicit. Closes #1146.

### CODE REVIEW

**Comment by Reinmar** [comment]
If this is fixing the selective undo scenario (as I understand from the ticket, which has no labels, so I don't know if it's a bug or not), could we have integration tests for that?

**Comment by Reinmar** [comment]
Bump?

**Comment by scofalik** [comment]
An old issue ;). But I'll try to remind and come up with a test case.

**Comment by scofalik** [comment]
So I've added an integration test here: https://github.com/ckeditor/ckeditor5-undo/pull/74.

To sum up: the transformation algorithm in deltas transformation case for `SplitDelta` x `SplitDelta` is incorrect for a special case, when both deltas try to return the same node from graveyard. This should happen only when undo is used in a specific scenario. Since the transformation should not be fired when undo is used I'd rather make sure that it is "turned off" rather than try to fix the algorithm.

**Comment by Reinmar** [comment]
I guess we need to update the code added in https://github.com/ckeditor/ckeditor5-engine/pull/1150 to work with this changes. I'll check what I can do myself.

**Pull request merged**
